site_name: Pegasus Docs
site_url: http://www.pegasus-frontend.org
site_description: Documentation and customization guides for the Pegasus frontend.
site_author: Mátyás Mustoha

repo_url: https://github.com/mmatyas/pegasus-frontend/

pages:
    - Home: index.md
    - About: about.md

theme: cinder
extra_css:
    - https://fonts.googleapis.com/icon?family=Material+Icons
    - css/extra.css

markdown_extensions:
    - toc:
        separator: "_"
    - sane_lists
    - admonition
    - def_list
plugins:
    - search
