site_name: Pegasus Docs
site_url: http://www.pegasus-frontend.org
site_description: Documentation and customization guides for the Pegasus frontend.
site_author: Mátyás Mustoha

repo_url: https://github.com/mmatyas/pegasus-frontend/

pages:
    - Home: index.md
    - User Guide:
        - Controls: user-guide/controls.md
        - Scripting: user-guide/scripting.md
    - Development:
        - Installing Qt: dev/install-qt.md
        - Cross compile Qt: dev/cross-compile-qt.md
        - Building: dev/build.md
        - Deployment: dev/deploy.md
        - Translations: dev/translate.md

theme: cinder
extra_css:
    - https://fonts.googleapis.com/icon?family=Material+Icons
    - css/extra.css

markdown_extensions:
    - toc
    - sane_lists
    - admonition
    - def_list
